### ISSUE TITLE
Error loading script: asymmetric_tiling.py

### ISSUE THREAD

**Issue by jeranon** [tjm35/asymmetric-tiling-sd-webui#1]
I got this when I tried loading this script:
`Error loading script: asymmetric_tiling.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "E:\stable-diffusion-webui\scripts\asymmetric_tiling.py", line 70
    <title>asymmetric-tiling-sd-webui/asymmetric_tiling.py at main · tjm35/asymmetric-tiling-sd-webui</title>
                                                                   ^
SyntaxError: invalid character '·' (U+00B7)`

**Comment by jeranon** [comment]
> Perhaps check that you've downloaded the file correctly? The "line 70" in that error message doesn't resemble any line in the actual `asymmetric_tiling.py` file, it looks like it has some html in there. The downloaded `asymmetric_tiling.py` file should only contain [this text](https://raw.githubusercontent.com/tjm35/asymmetric-tiling-sd-webui/main/asymmetric_tiling.py).

That fixed it... turns out I'm just an idiot who knows nothing about GitHub!! I appreciate you taking the time. I think what happened was I had accidentally saved the entire github page as the .py file somehow... 
Regardless. I've closed this.
Cheers!
